### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [psiphi75/x3-rust#1]
Dear @psiphi75, could you be so kind to generate .exe for Windows 7 x64? I am not a developer, but an ordinary user, so I might mess something up and get a suboptimal result, but I really want to try your encoder in practice.

**Comment by psiphi75** [comment]
First, I'm not creating binaries (.exe files) for any platform.  Second, Windows 7 is very old and I don't know if the Rust compiler supports it, so it may be impossible to compile for Windows 7.  But below are instructions for getting it going yourself.

You can install rustup (the rust installer) for Windows, just read the "Install Rust" section here: https://learn.microsoft.com/en-us/windows/dev-environment/rust/setup#install-rust

Then just run (this will download and compile the x3 executable):

```sh
cargo install x3
```

Then run `x3` using something like the following:

```sh
x3 --input /path/to/file.wav --output /path/to/file.x3a
```

**Comment by psiphi75** [comment]
@sergeevabc, did it work?

**Comment by sergeevabc** [comment]
@psiphi75 I don't know yet. First we need a hero who is good at compiling code (it's not me, alas). Perhaps one day such a person will come across this discussion and attach an executable file here.
